name: Validate Branch
on: [push]

jobs:
  prettier:
    name: Check Prettier Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
      - name: Install deps
        run: pnpm install --ignore-scripts
      - name: Run Prettier
        run: pnpm prettier:ci
  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
      - name: Install deps
        run: pnpm install --ignore-scripts
      - name: Run ESLint
        run: pnpm eslint
